#!/usr/bin/env python3
"""Generates assets/models/torus.obj — Forge's committed import-test model.

Provenance for the repo: this torus is procedurally generated (no external
asset, no license questions). Regenerate with:  python tools/gen_torus.py
Positions + smooth normals + UVs; faces are CCW-outward triangles, matching
the engine's winding convention (ADR-012).
"""

import math
import os

RING_RADIUS = 0.6   # center of tube from torus center
TUBE_RADIUS = 0.25
RING_SEGMENTS = 32  # around the big circle
TUBE_SEGMENTS = 16  # around the tube


def main() -> None:
    out_path = os.path.join(os.path.dirname(__file__), "..", "assets", "models", "torus.obj")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    lines = ["# Generated by tools/gen_torus.py - do not hand-edit.",
             "o torus"]

    for i in range(RING_SEGMENTS):
        theta = 2.0 * math.pi * i / RING_SEGMENTS          # around the ring (Y axis)
        ring = (math.cos(theta), math.sin(theta))
        for j in range(TUBE_SEGMENTS):
            phi = 2.0 * math.pi * j / TUBE_SEGMENTS        # around the tube
            # Tube cross-section: outward along the ring + up.
            cx, cz = RING_RADIUS * ring[0], RING_RADIUS * ring[1]
            nx = math.cos(phi) * ring[0]
            nz = math.cos(phi) * ring[1]
            ny = math.sin(phi)
            x = cx + TUBE_RADIUS * nx
            y = TUBE_RADIUS * ny
            z = cz + TUBE_RADIUS * nz
            u = i / RING_SEGMENTS * 3.0                     # wrap the checker 3x
            v = j / TUBE_SEGMENTS
            lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
            lines.append(f"vn {nx:.6f} {ny:.6f} {nz:.6f}")
            lines.append(f"vt {u:.6f} {v:.6f}")

    def idx(i: int, j: int) -> int:  # 1-based OBJ index
        return (i % RING_SEGMENTS) * TUBE_SEGMENTS + (j % TUBE_SEGMENTS) + 1

    for i in range(RING_SEGMENTS):
        for j in range(TUBE_SEGMENTS):
            a, b = idx(i, j), idx(i + 1, j)
            c, d = idx(i + 1, j + 1), idx(i, j + 1)
            # Two CCW-outward triangles per quad. Verified with pixels, not
            # algebra: (a,b,c) order renders inside-out (cross(dTheta,dPhi)
            # points INTO the tube), so wind (a,c,b) / (a,d,c).
            lines.append(f"f {a}/{a}/{a} {c}/{c}/{c} {b}/{b}/{b}")
            lines.append(f"f {a}/{a}/{a} {d}/{d}/{d} {c}/{c}/{c}")

    with open(out_path, "w", encoding="ascii", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.normpath(out_path)}: "
          f"{RING_SEGMENTS * TUBE_SEGMENTS} vertices, {RING_SEGMENTS * TUBE_SEGMENTS * 2} triangles")


if __name__ == "__main__":
    main()
