# cmake/EmbedShaders.cmake
#
# Turns checked-in .spv files into a generated C++ header of uint32_t arrays
# (ADR-011). Pure CMake: no Vulkan SDK, no external tool, no runtime file I/O
# — vkCreateShaderModule reads the arrays straight out of the binary.
#
#   forge_embed_spirv(<out_header> <name1> <path1> [<name2> <path2> ...])
#
# emits `inline constexpr uint32_t <nameN>[] = {...};` per pair, inside
# namespace forge::shaders. Reconfigures automatically when a .spv changes.

function(forge_embed_spirv out_header)
    set(body "")
    list(LENGTH ARGN argn_len)
    math(EXPR last_pair "${argn_len} / 2 - 1")
    foreach(pair RANGE ${last_pair})
        math(EXPR name_idx "${pair} * 2")
        math(EXPR path_idx "${name_idx} + 1")
        list(GET ARGN ${name_idx} name)
        list(GET ARGN ${path_idx} path)

        file(READ "${path}" hex HEX)
        # SPIR-V is a stream of little-endian 32-bit words on disk: regroup
        # each 4 bytes (8 hex chars) reversed into a 0x-literal.
        string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1," words "${hex}")
        string(APPEND body "inline constexpr uint32_t ${name}[] = {${words}};\n\n")

        # Re-run configure (and so regenerate) when the .spv is recompiled.
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
    endforeach()

    file(WRITE "${out_header}"
        "// Generated by cmake/EmbedShaders.cmake — DO NOT EDIT.\n"
        "#pragma once\n"
        "#include <cstdint>\n\n"
        "namespace forge::shaders {\n\n"
        "${body}"
        "} // namespace forge::shaders\n")
endfunction()
